### ISSUE TITLE
Analysing Deep Reinforcement Learning Agents Trained with Domain Randomisation

### ISSUE THREAD

**Issue by Kaixhin** [distillpub/post--understanding-rl-vision#17]
This was a really beautiful article with some fantastic results on visual attribution. With respect to some of your hypotheses, methodology, and questions for further research, you may find the results from [Analysing Deep Reinforcement Learning Agents Trained with Domain Randomisation](https://arxiv.org/abs/1912.08324v2) relevant. In particular:

- We apply a range of interpretability measures to understand how visual procedural generation affects DRL agents
- Using domain randomisation to make the training distribution more diverse results in more interpretable features (Sec. 4.2)
- In contrast to normal expectations on interpretability and generalisation, it is possible for agents trained with diverse data to "overfit" (Sec. 3.3)
- In contrast to your setup, we did find that applying regularisers to activation maximisation did help (Sec. 2.2.2); it is possible that with a shallower network you might have found more interpretable maps
- We study generalisation by using a basic subset of domain randomisation properties and testing against reasonable out-of-distribution settings (Sec. 3.4)
- We study two tasks of differing difficulty, but this does not seem to impact interpretability (in our experiments at least)
- There are 2 quantitative metrics that we use that might relate to interpretability, power spectral entropy (Sec. 2.2.4) and entanglement (Sec 2.2.8)

**Comment by jacobhilton** [comment]
Thanks so much for drawing our attention to this highly relevant paper. It is very interesting to compare and contrast the two domains. I have pushed an update to the article accordingly.
